### PR TITLE
Fix dereferencing of LPDWORD lpNumberOfBytesRead in ReadFile() and LPDWO...

### PR DESCRIPTION
**Pull request by planteen**
...RD lpNumberOfBytesWritten in  WriteFile() calls to Windows FFI

### CODE REVIEW

**Comment by zankich** [comment]
@planteen if I remember correctly, the reason why we don't use `read_int` is because it does not work with Jruby. Did you test this with Jruby?

**Comment by planteen** [comment]
@zankich No, Ruby MRI (ruby 2.0.0p598 (2014-11-13) [i386-mingw32])

**Comment by zankich** [comment]
@planteen I don't have access to a windows machine at the moment, can you test this with Jruby?

**Comment by planteen** [comment]
@zankich Confirmed issue #19  was present with JRuby. Tested this fix with both `jruby --2.0` and `jruby --1.9`. Fix resolved issue under both versions.

**Comment by zankich** [comment]
Great, thanks for the pull request!

**Pull request merged**
