### PR TITLE
Allow reading zero-bytes (0x00) using getbyte.

### PR DESCRIPTION
**Pull request by donv**
We experienced getting nil instead of a zero byte when reading using getbyte.

Can this make the 0.2.2 release?   :smile:

### CODE REVIEW

**Comment by donv** [comment]
Hi!

I see the tests fail in travis, but they succeed for me locally on Linux and OS X.  Do they pass for you?

**Comment by donv** [comment]
Hi!

OK, travis build is green!  Any chance this can be merged and released?

**Comment by zankich** [comment]
@donv ah yes so your source is sending you a null character, but rubyserial is passing it along as a ruby `nil` and not the `0x00`. A similar change is required for the windows implementation so that we have consistent behavior between both platforms https://github.com/hybridgroup/rubyserial/blob/master/lib/rubyserial/windows.rb#L64

**Comment by donv** [comment]
@zankich yes.  Do we need to fix it for windows before merging this PR?

**Comment by zankich** [comment]
@donv yes if you wouldn't mind making the change and then we can test to make sure the behavior is correct, thanks!

**Comment by donv** [comment]
Hi @zankich !

I do not have a Windows development environment, and I don't want to invest in that now.  It would be great if you could add the fix for non-windows users, and a contributor on windows could fix it for windows.

Is that doable?

**Comment by zankich** [comment]
@donv yes I'll merge this now and get the windows fix in place, thanks for the pull request!

**Pull request merged**
